@startuml

!include <C4/C4_Container>

Person(client, "Client", "Пользователь системы")
Person(customerSupportTeam, "CustomerSupportTeam", "Команда по обслуживанию клиентов")
System_Boundary(platform, "Умный дом") {
    Container(clientFrontend, "Client web interface", "Client frontend")
    Container(supportFrontend, "Support web interface", "Support Team frontend")
    Container(apiGateway, "API Gateway", "API Gateway")
    Container(userManagement, "User Management", "Сервис управления пользователями")
    Container(telemetry, "Telemetry", "Сервис телеметрии")
    Container(automation, "Automation", "Сервис автоматизации")
    Container(deviceManagementService, "DeviceManagement", "Сервис управления устройствами")
    Container(marketplace, "Marketplace", "Маркет, каталог устройств")
    Container(integrationHub, "Integration Hub", "Сервис интеграции с устройствами партнеров")
    System(microcontrollers, "Microcontrollers/Modules", "Устройства умного дома")
}

Rel(client, clientFrontend, "Управление и мониторинг\n умным домом", "HTTP")
Rel(customerSupportTeam, supportFrontend, "Поддержка пользователей", "HTTP")
Rel(clientFrontend, apiGateway, "client requests", "HTTP")
Rel(supportFrontend, apiGateway, "support requests", "HTTP")
Rel(apiGateway, deviceManagementService, "Управление устройствами", "HTTP")
Rel(apiGateway, automation, "Управление и получение сценариев", "HTTP")
Rel(automation, deviceManagementService, "Управление устройствами", "HTTP")
Rel_R(apiGateway, marketplace, "Продажи в интернет-магазине", "HTTP")
Rel_L(apiGateway, userManagement, "Управление и информация о пользователях" ,"HTTP")
Rel(deviceManagementService, integrationHub, "Управление устройствами", "HTTP")
Rel(integrationHub, microcontrollers, "Управление конечными устройствами", "MQTT/Zigbee")
Rel(telemetry, integrationHub, "Получение телеметрии с устройств", "HTTP")
Rel(deviceManagementService, telemetry, "Изменение состояний устройств телеметрии", "HTTP")
Rel(apiGateway, telemetry, "Получение телеметрии с устройств", "HTTP")




@enduml