@startuml
!include <C4/C4_Component>

Container_Boundary(userManagement, "User Management Service") {
    Component(userApi, "User API", "REST API", "Обработка HTTP запросов для операций с пользователями")
    Component(userService, "User Service", "Go Service", "Бизнес-логика управления пользователями")
    Component(userDBService, "User DB service", "SQL/Go", "Слой доступа к данным пользователей")
    ComponentDb(userDb, "User Database", "PostgreSQL", "Хранение данных пользователей")
}

Rel(userApi, userService, "Вызов бизнес-логики", "Go func")
Rel(userService, userDBService, "Чтение/запись данных", "Go func")
Rel(userDBService, userDb, "SQL запросы", "SQL")

@enduml